/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10.2/samples
 */
group = "br.gov.bndes.rbb"
version = "1.0.0-SNAPSHOT"

plugins {
    id("java")
}


//usado para as dependências
repositories {
    maven { 
        isAllowInsecureProtocol = true
        
        url = uri("http://mvnrepo.bndes.net:8180/nexus/content/groups/public/")
        credentials{ 
            username = project.findProperty("repoUsername") as String?
            password = project.findProperty("repoPassword") as String?
        }
    }
}

dependencies {
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.13.1")
    implementation("info.picocli:picocli:4.7.6")

    // annotationProcessor generates the file META-INF/services/org.hyperledger.besu.plugin.BesuPlugin
    annotationProcessor("com.google.auto.service:auto-service:1.0")

    implementation("com.google.auto.service:auto-service:1.0")
    implementation("io.tmio:tuweni-bytes:2.4.2")
    implementation("io.tmio:tuweni-units:2.4.2")

    implementation("org.bouncycastle:bcprov-jdk18on:1.77")
    
    implementation("org.hyperledger.besu:plugin-api:24.8.0")
    implementation("org.hyperledger.besu:besu-datatypes:24.8.0") 
    implementation("org.hyperledger.besu:evm:24.8.0") 
    implementation("org.hyperledger.besu:api:24.8.0") 
    implementation("org.hyerledger.besu:crypto:23.1.3")
    implementation("org.hyperledger.besu:core:24.8.0")
    implementation("org.hyperledger.besu:permissioning:24.8.0")
}

buildscript {
    repositories {
        maven { 
            isAllowInsecureProtocol = true
            
            url = uri("http://mvnrepo.bndes.net:8180/nexus/content/groups/public/")
            credentials{ 
                username = project.findProperty("repoUsername") as String?
                password = project.findProperty("repoPassword") as String?
            }
        }
    }
    dependencies {
        classpath("com.github.johnrengelman:shadow:8.1.1")
    }

    
}
apply(plugin = "com.github.johnrengelman.shadow")