/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10.2/samples
 */
group = "rbb"
version = "1.0.0-SNAPSHOT"

plugins {
    id("java")
     id("com.github.johnrengelman.shadow") version "8.1.1"
}


//usado para as dependências
repositories {
    maven {
      url = uri("https://hyperledger.jfrog.io/hyperledger/besu-maven")
      content { includeGroupByRegex("org\\.hyperledger\\..*") }
    }
    maven {
      url = uri("https://artifacts.consensys.net/public/maven/maven/")
      content { includeGroupByRegex("tech\\.pegasys(\\..*)?") }
    }
    mavenCentral()
}

dependencies {
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.13.1")
    implementation("info.picocli:picocli:4.7.6")

    // annotationProcessor generates the file META-INF/services/org.hyperledger.besu.plugin.BesuPlugin
    annotationProcessor("com.google.auto.service:auto-service:1.0")

    implementation("com.google.auto.service:auto-service:1.0")
    implementation("io.tmio:tuweni-bytes:2.4.2")
    implementation("io.tmio:tuweni-units:2.4.2")

    implementation("org.bouncycastle:bcprov-jdk18on:1.77")
    
    implementation("org.hyperledger.besu:plugin-api:24.8.0")
    implementation("org.hyperledger.besu:besu-datatypes:24.8.0") 
    implementation("org.hyperledger.besu:evm:24.8.0") 
    implementation("org.hyperledger.besu.internal:api:24.8.0") 
    implementation("org.hyperledger.besu.internal:crypto:23.1.3")
    implementation("org.hyperledger.besu.internal:core:24.8.0")
    implementation("org.hyperledger.besu.internal:permissioning:24.8.0")
}
